-- Demo-Listings für Phase-0-Showcase.
-- Idempotent via (source, dedup_hash). Real-Daten folgen aus Indexer + Direkteinpflege.

insert into listings (
  source, external_id, type, status,
  location_city, location_district, location_raw,
  price, currency, price_period,
  rooms, size_sqm,
  contact_name, contact_channel, language,
  dedup_hash
) values
  ('direct', 'demo-1', 'rent', 'active',
   'Paphos', 'Kato Paphos', 'Paphos, Kato',
   950, 'EUR', 'month', 1, 48,
   'Demo Owner 1', 'whatsapp', 'en',
   'demo-paphos-kato-1z-950'),
  ('direct', 'demo-2', 'rent', 'active',
   'Paphos', 'Chloraka', 'Paphos, Chloraka',
   1200, 'EUR', 'month', 2, 72,
   'Demo Owner 2', 'whatsapp', 'en',
   'demo-paphos-chloraka-2z-1200'),
  ('direct', 'demo-3', 'rent', 'active',
   'Paphos', 'Universal', 'Paphos, Universal',
   1450, 'EUR', 'month', 2, 80,
   'Demo Owner 3', 'whatsapp', 'en',
   'demo-paphos-universal-2z-1450'),
  ('direct', 'demo-4', 'rent', 'active',
   'Paphos', 'Tombs of the Kings', 'Paphos, Tombs of the Kings',
   1700, 'EUR', 'month', 3, 110,
   'Demo Owner 4', 'telegram', 'en',
   'demo-paphos-tombs-3z-1700'),
  ('direct', 'demo-5', 'rent', 'active',
   'Paphos', 'Yeroskipou', 'Paphos, Yeroskipou',
   2200, 'EUR', 'month', 3, 140,
   'Demo Owner 5', 'whatsapp', 'en',
   'demo-paphos-yeroskipou-3z-2200'),
  ('direct', 'demo-6', 'rent', 'active',
   'Limassol', 'Tourist Area', 'Limassol, Tourist Area',
   1400, 'EUR', 'month', 2, 75,
   'Demo Owner 6', 'whatsapp', 'ru',
   'demo-limassol-tourist-2z-1400'),
  ('direct', 'demo-7', 'rent', 'active',
   'Limassol', 'Germasogeia', 'Limassol, Germasogeia',
   1800, 'EUR', 'month', 2, 85,
   'Demo Owner 7', 'telegram', 'ru',
   'demo-limassol-germasogeia-2z-1800'),
  ('direct', 'demo-8', 'rent', 'active',
   'Limassol', 'Agios Athanasios', 'Limassol, Agios Athanasios',
   1100, 'EUR', 'month', 1, 55,
   'Demo Owner 8', 'whatsapp', 'en',
   'demo-limassol-athanasios-1z-1100'),
  ('direct', 'demo-9', 'rent', 'active',
   'Nicosia', 'Engomi', 'Nicosia, Engomi',
   850, 'EUR', 'month', 2, 70,
   'Demo Owner 9', 'whatsapp', 'el',
   'demo-nicosia-engomi-2z-850'),
  ('direct', 'demo-10', 'rent', 'active',
   'Larnaca', 'Finikoudes', 'Larnaca, Finikoudes',
   950, 'EUR', 'month', 2, 65,
   'Demo Owner 10', 'whatsapp', 'en',
   'demo-larnaca-finikoudes-2z-950')
on conflict (source, dedup_hash) do nothing;
